# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.encryptGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.encryptGroup.setObjectName("encryptGroup")
        self.encryptLayout = QtWidgets.QVBoxLayout(self.encryptGroup)
        self.encryptLayout.setObjectName("encryptLayout")
        self.encryptInputLayout = QtWidgets.QHBoxLayout()
        self.encryptInputLayout.setObjectName("encryptInputLayout")
        self.encryptPlainLabel = QtWidgets.QLabel(self.encryptGroup)
        self.encryptPlainLabel.setObjectName("encryptPlainLabel")
        self.encryptInputLayout.addWidget(self.encryptPlainLabel)
        self.encryptPlainText = QtWidgets.QLineEdit(self.encryptGroup)
        self.encryptPlainText.setObjectName("encryptPlainText")
        self.encryptInputLayout.addWidget(self.encryptPlainText)
        self.encryptLayout.addLayout(self.encryptInputLayout)
        self.encryptKeyLayout = QtWidgets.QHBoxLayout()
        self.encryptKeyLayout.setObjectName("encryptKeyLayout")
        self.encryptKeyLabel = QtWidgets.QLabel(self.encryptGroup)
        self.encryptKeyLabel.setObjectName("encryptKeyLabel")
        self.encryptKeyLayout.addWidget(self.encryptKeyLabel)
        self.encryptKey = QtWidgets.QLineEdit(self.encryptGroup)
        self.encryptKey.setObjectName("encryptKey")
        self.encryptKeyLayout.addWidget(self.encryptKey)
        self.encryptLayout.addLayout(self.encryptKeyLayout)
        self.encryptBtn = QtWidgets.QPushButton(self.encryptGroup)
        self.encryptBtn.setObjectName("encryptBtn")
        self.encryptLayout.addWidget(self.encryptBtn)
        self.encryptResultLabel = QtWidgets.QLabel(self.encryptGroup)
        self.encryptResultLabel.setObjectName("encryptResultLabel")
        self.encryptLayout.addWidget(self.encryptResultLabel)
        self.encryptResult = QtWidgets.QTextEdit(self.encryptGroup)
        self.encryptResult.setReadOnly(True)
        self.encryptResult.setMaximumSize(QtCore.QSize(16777215, 60))
        self.encryptResult.setObjectName("encryptResult")
        self.encryptLayout.addWidget(self.encryptResult)
        self.verticalLayout.addWidget(self.encryptGroup)
        self.decryptGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.decryptGroup.setObjectName("decryptGroup")
        self.decryptLayout = QtWidgets.QVBoxLayout(self.decryptGroup)
        self.decryptLayout.setObjectName("decryptLayout")
        self.decryptInputLayout = QtWidgets.QHBoxLayout()
        self.decryptInputLayout.setObjectName("decryptInputLayout")
        self.decryptCipherLabel = QtWidgets.QLabel(self.decryptGroup)
        self.decryptCipherLabel.setObjectName("decryptCipherLabel")
        self.decryptInputLayout.addWidget(self.decryptCipherLabel)
        self.decryptCipherText = QtWidgets.QLineEdit(self.decryptGroup)
        self.decryptCipherText.setObjectName("decryptCipherText")
        self.decryptInputLayout.addWidget(self.decryptCipherText)
        self.decryptLayout.addLayout(self.decryptInputLayout)
        self.decryptKeyLayout = QtWidgets.QHBoxLayout()
        self.decryptKeyLayout.setObjectName("decryptKeyLayout")
        self.decryptKeyLabel = QtWidgets.QLabel(self.decryptGroup)
        self.decryptKeyLabel.setObjectName("decryptKeyLabel")
        self.decryptKeyLayout.addWidget(self.decryptKeyLabel)
        self.decryptKey = QtWidgets.QLineEdit(self.decryptGroup)
        self.decryptKey.setObjectName("decryptKey")
        self.decryptKeyLayout.addWidget(self.decryptKey)
        self.decryptLayout.addLayout(self.decryptKeyLayout)
        self.decryptBtn = QtWidgets.QPushButton(self.decryptGroup)
        self.decryptBtn.setObjectName("decryptBtn")
        self.decryptLayout.addWidget(self.decryptBtn)
        self.decryptResultLabel = QtWidgets.QLabel(self.decryptGroup)
        self.decryptResultLabel.setObjectName("decryptResultLabel")
        self.decryptLayout.addWidget(self.decryptResultLabel)
        self.decryptResult = QtWidgets.QTextEdit(self.decryptGroup)
        self.decryptResult.setReadOnly(True)
        self.decryptResult.setMaximumSize(QtCore.QSize(16777215, 60))
        self.decryptResult.setObjectName("decryptResult")
        self.decryptLayout.addWidget(self.decryptResult)
        self.verticalLayout.addWidget(self.decryptGroup)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caesar Cipher"))
        self.encryptGroup.setTitle(_translate("MainWindow", "Encrypt"))
        self.encryptPlainLabel.setText(_translate("MainWindow", "Plain Text:"))
        self.encryptKeyLabel.setText(_translate("MainWindow", "Key:"))
        self.encryptBtn.setText(_translate("MainWindow", "Encrypt"))
        self.encryptResultLabel.setText(_translate("MainWindow", "Encrypted Text:"))
        self.decryptGroup.setTitle(_translate("MainWindow", "Decrypt"))
        self.decryptCipherLabel.setText(_translate("MainWindow", "Cipher Text:"))
        self.decryptKeyLabel.setText(_translate("MainWindow", "Key:"))
        self.decryptBtn.setText(_translate("MainWindow", "Decrypt"))
        self.decryptResultLabel.setText(_translate("MainWindow", "Decrypted Text:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
